### ISSUE TITLE
Localize Word toolbar

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#3314] opened 2023-08-12 11:53 UTC
https://forums.zotero.org/discussion/106857/installation-de-zotero-dans-word-en-anglais-et-non-en-francais

Is there any mechanism for this in the template?

**Comment by adomasven** [comment] 2023-08-12 15:27
Not with the template, but with the word js api there is.

**Comment by adomasven** [comment] 2023-08-12 15:29
Also a duplicate of https://github.com/zotero/zotero-word-for-windows-integration/issues/18

**Closed by adomasven** 2023-08-12 15:29 UTC
Labels: Word Processor Integration
