### ISSUE TITLE
PDF Reader: Keep unused tabs out of memory

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2383] opened 2022-03-04 09:18 UTC
https://forums.zotero.org/discussion/94546/possible-mac-memory-issue

How hard would it be to 1) not load PDF tabs at startup until they're first accessed and 2) unload tabs after a certain amount of time of inactivity?

Particularly (1) would be good, if we're not doing that — that's always been one of my favorite features of Firefox.

**Comment by mrtcode** [comment] 2022-03-04 16:29
I can't say how hard it would be until I'll start implementing this, but hopefully not too hard. If we implement 1), then 2) should be relatively easy.

Should we add "Zotero 6" milestone for this issue?

**Comment by dstillman** [comment] 2022-03-04 18:53
No, this isn't a blocker.

**Comment by mrtcode** [comment] 2022-03-16 14:58
I was able to reproduce a memory leak by artificially creating errors when opening a PDF. Not clear what exactly is leaking, but after opening/closing the same PDF (bitcoin.pdf) up to 30 times, the memory usage was 3GB. I'll continue the investigation.

**Comment by mrtcode** [comment] 2022-03-17 11:09
I'm not able to reproduce the issue in real life scenarios. I was manually removing one pdf-reader iframe over dev tools (to explore methods to unload the tab), which resulted in ghost window which was growing each time when another PDF is opened and closed. `heap-unclassified` was also growing proportially, but it's probably related to that window.

Although I found that PDF worker after heavy use also leaks memory, but I'll create a new issue for that.

**Comment by mrtcode** [comment] 2022-03-18 14:07
Tab unloading is mostly implemented. A placeholder tab will be swapped with the actual tab, and the opposite.

For now I suggest to:
1. Keep all tabs unloaded on Zotero opening.
2. Keep loaded only the last five selected tabs.
3. Keep loaded only in the last 24h selected tabs.

Does it sound good? I'll prepare a PR if so.

**Comment by dstillman** [comment] 2022-03-18 17:28
That sounds great.

**Closed** 2022-04-20 07:14 UTC
Labels: P2
