### ISSUE TITLE
Highlighted text from Word not highlighted on paste

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2455] opened 2022-03-23 07:08 UTC
https://forums.zotero.org/discussion/95477/highlighting-in-notes

Not tested

**Comment by mrtcode** [comment] 2022-03-23 13:19
I don't have Word installed at the moment, but I tested with Pages.app, and yes, it doesn't work. The problem is that CSS styles aren't inlined. I guess the same problem is with Word. Works ok with Google Docs.

None of the ProseMirror based editors that I tested support this. I guess this is a bit complicated because parsing happens over DOMParser where style computations can't happen. Pasting into contenteditable also works well, but this is not how PM works. There are multi-megabyte libraries that allow to inline CSS, but that doesn't sound good.

The best option would probably be to hand code style inlining for each popular word processor. It would also be possible to insert the HTML into the main document and apply computed styling here. But there might be downsides. I'll investigate this further.

Pages.app gives:
```html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="Content-Style-Type" content="text/css">
<title></title>
<meta name="Generator" content="Cocoa HTML Writer">
<meta name="CocoaVersion" content="2113.3">
<style type="text/css">
p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px 'Helvetica Neue'; color: #53d52a; background-color: #fc2190}
p.p2 {margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px 'Helvetica Neue'; color: #53d52a; background-color: #fc2190; min-height: 12.0px}
p.p3 {margin: 0.0px 0.0px 0.0px 0.0px; font: 24.0px 'Helvetica Neue'; color: #53d52a; background-color: #fc2190}
p.p4 {margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px 'Helvetica Neue'; color: #000000; background-color: #fc2190}
p.p5 {margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px 'Helvetica Neue'; color: #000000; background-color: #fc2190; min-height: 12.0px}
</style>
</head>
<body>
<p class="p1">wefwfwwfwfwef</p>
<p class="p2"><br></p>
<p class="p2"><br></p>
<p class="p2"><br></p>
<p class="p3">Wefwefwefwef</p>
<p class="p2"><br></p>
<p class="p4">Vtyggy</p>
<p class="p5"><br></p>
<p class="p5"><br></p>
<p class="p4">W</p>
<p class="p4">Efwefwefwefwefwe</p>
<p class="p5"><br></p>
<p class="p5"><br></p>
<p class="p5"><br></p>
<p class="p4"><b>wefewfewfefwef</b></p>
</body>
</html>
```

**Comment by mrtcode** [comment] 2022-04-07 13:37
Fixed in https://github.com/zotero/note-editor/commit/c9b82177781a2dcb5f122247221fc886adf2ed87. The same problem was with LibreOffice. Let's ignore Pages.app for now.

**Closed by mrtcode** 2022-04-07 13:37 UTC
Labels: Regression, PDF Reader, Bug
