### ISSUE TITLE
No way to set the default PDF for multi-file attachments

### ISSUE THREAD

**Issue by Stannislav** [zotero/zotero#1505] opened 2018-05-23 09:34 UTC
A double click on a Zotero entry with a file attached to it opens that file in the system viewer set up for it, e.g. the Adobe Reader for PDFs. When multiple files are attached a double click opens one of them, which I believe is determined by the chronological order in which the attachments were added. It would be nice to have a setting that allowed one to specify which file will be opened upon double-clicking.

**Comment by 0Hughman0** [comment] 2020-01-16 13:49
I am also massively suffering from this issue (I had the same issue with Mendeley Desktop).

This is a massive pain when adding supplementary notes to entries. On double click I always want to open the main article, but when I add the supplementary notes to an entry, this new document is set as the default. 

I will only add supplementary notes to entries that I am particularly interested in.

Version: 5.0.81

**Comment by dstillman** [comment] 2020-01-16 19:49
> when I add the supplementary notes to an entry, this new document is set as the default

Zotero opens the first PDF added to the item, so that shouldn't be the case. If you think you're seeing something different, you should report it in the Zotero Forums.

**Comment by dstillman** [comment] 2020-01-16 19:51
Duplicate of https://github.com/zotero/zotero/issues/355

**Closed by dstillman** 2020-01-16 19:51 UTC
