### ISSUE TITLE
Can't navigate items list with unmodified arrow keys in JAWS?

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4030] opened 2024-04-22 00:01 UTC
https://forums.zotero.org/discussion/113872/zotero-7-beta-accessibility-with-jaws

**Comment by abaevbog** [comment] 2024-04-22 03:44
Related to: #3930

**Comment by abaevbog** [comment] 2024-04-22 03:59
Hm, though I can't yet reproduce the necessity to hold Ctrl to navigate the itemTree. It has been a known issue that JAWS struggles with announcing the row during navigation (it begins announcing some of itemBox entries) but I don't experience any issues with the actual arrow navigation on win 11, the last version of JAWS that I just reset to factory setting. I wonder if the issue could be caused by the JAWS configuration...

**Comment by abaevbog** [comment] 2024-06-04 20:22
Duplicate of #4144. Fixed by https://github.com/zotero/zotero/commit/17255e4f5b28a5a7d20735319fe213cadbcbdccd. Remaining JAWS issues discussed in https://github.com/zotero/zotero/issues/3930.

**Closed by abaevbog** 2024-06-04 20:22 UTC
Labels: Accessibility
