### ISSUE TITLE
Warning if connector port is taken

### ISSUE THREAD

**Issue by cossio** [zotero/zotero#1484] opened 2018-04-12 15:25 UTC
Zotero should warn if it cannot listen on port 23119.

It happened to me a bunch of times that Zotero Connector stopped working. I finally diagnosed that Foxit Reader (on Linux) listens on port 23119 as well (I don't know why). So whenever I opend Foxit reader before opening Zotero, the Connector wasn't able to claim the port.

**Comment by adomasven** [comment] 2018-04-21 17:31
Duplicate of #1409

**Closed by adomasven** 2018-04-21 17:31 UTC
