### ISSUE TITLE
Localization of Update Dialog

### ISSUE THREAD

**Issue by zuphilip** [zotero/zotero#1281] opened 2017-08-05 16:34 UTC
The update dialog (picture 2 and 3) seems not to be localized, but it is in English also for my German version of Zotero:

![update-dialog-1](https://user-images.githubusercontent.com/5199995/28997041-3a253fa6-7a0c-11e7-8161-fa310b487aba.jpg)
![update-dialog-2](https://user-images.githubusercontent.com/5199995/28997037-2e7de888-7a0c-11e7-95e7-69ef842a3884.jpg)
![update-dialog-3](https://user-images.githubusercontent.com/5199995/28997038-2ffb42aa-7a0c-11e7-9201-860d25478368.jpg)

**Comment by gracile-fr** [comment] 2017-08-06 22:35
Duplicate of https://github.com/zotero/zotero-standalone-build/issues/30

**Closed** 2017-08-07 00:42 UTC
