### ISSUE TITLE
Fix accessibility of retraction banner

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2655] opened 2022-06-14 23:41 UTC
https://forums.zotero.org/discussion/97819/accessibility-retraction-notice

We can do this on the fx102 branch, maybe switching to the built-in text-link CE, which automatically handles Return == click().

In addition to keyboard access, we should set an appropriate ARIA label on this and other notification banners. Not sure whether [the `alert` role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/alert_role) or [`aria-live`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-live) is more appropriate.

**Comment by dstillman** [comment] 2022-07-05 21:28
This is about the banner that appears across top of the window. Click an item, run `Zotero.Prefs.set('retractions.recentItems', '[' + ZoteroPane.getSelectedItems()[0].id + ']');`, and restart.

**Comment by AbeJellinek** [comment] 2022-07-05 22:01
Oops, right, thanks.

**Comment by AbeJellinek** [comment] 2022-08-04 18:54
Fixed by 617ede481abcfc0eb070d1015f4a362f22e2bc6a

**Closed** 2022-08-04 18:54 UTC
Labels: Accessibility

**Comment by abaevbog** [comment] 2024-01-18 05:30
It’s a long shot but this is the only somewhat related issue I could find to what I am trying to achieve in #3464 so I thought I would ask here.

I’ve been trying to set up a component with `aria-live` property to get screen readers to announce a message placed within that component. The goal there is to announce instructions as to which keyboard shortcuts are available for each focusable component. The problem is that changing text inside of `aria-live` component doesn’t prompt the screen-reader to say anything. I believe `role="status”` for `retracted-items-container` is supposed to announce the message from the banner as well but when it shows up, "An item in your database has been retracted" doesn’t get announced for me. Generally, `aria-live` works with voiceover on a test [website](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions) opened with firefox for me.

It’s not a deal breaker but I wanted to check if we have any known issues that prevent components with `aria-live` attribute from announcing when the content changes?
