### ISSUE TITLE
Merge button can persist in item pane

### ISSUE THREAD

**Issue by yexingsha** [zotero/zotero#4254] opened 2024-06-18 06:17 UTC
<img width="343" alt="Screenshot 2024-06-18 at 01 13 10" src="https://github.com/zotero/zotero/assets/57771795/71441bd6-1033-4be5-a16b-4cf6029773f4">

Steps to reproduce:

1. Select a pair of duplicate items
2. Click the merge button
3. Click anywhere outside the menu
4. Switch to any other collection. The merge button now persists in the item pane, floating on top of everything.

**Comment by dstillman** [comment] 2024-06-18 10:36
Duplicate of https://github.com/zotero/zotero/issues/4240

**Closed by dstillman** 2024-06-18 10:36 UTC
Labels: Bug
