### ISSUE TITLE
Drag and drop in OSX is not working

### ISSUE THREAD

**Issue by Benjamin-Lee** [zotero/zotero#1538] opened 2018-07-31 20:13 UTC
As per #354, this is not working for me on OSX:

![gif](https://media.giphy.com/media/5hh16Gndb6OWrwFDLE/giphy.gif)

I have a fresh install of 5.0.54 and it does not appear to work. It does work if I drag the PDF directly into the window, however.

**Comment by dstillman** [comment] 2018-07-31 21:56
https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md

Please post feature requests and bug reports to the Zotero Forums, not this tracker.

Dupe of #354

**Closed by dstillman** 2018-07-31 21:56 UTC
