### ISSUE TITLE
PDF reader: Delete and rearrange pages?

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2457] opened 2022-03-23 07:39 UTC
https://forums.zotero.org/discussion/95417/deleting-pages-in-pdfs-6-0-1

Do we want to get into this? It's one of the main things people likely want to do in external editors, and the only way for that not to mess things up is for us to do it.

**Comment by mrtcode** [comment] 2022-03-23 11:04
It's easy to delete or rearrange pages, but PDF has to be reloaded after each operation, which makes things more complicated.

**Comment by mrtcode** [comment] 2022-03-23 11:34
I mean pdf-worker would need to do the deletion/rearrangement. pdf-reader doesn't have the capability to do that.

**Comment by mrtcode** [comment] 2022-04-27 07:52
Duplicate of #2561.

**Closed by mrtcode** 2022-04-27 07:52 UTC
Labels: Enhancement, PDF Reader
