### ISSUE TITLE
Some edits not saved when clicking away from field

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#4388] opened 2024-07-15 08:12 UTC
https://forums.zotero.org/discussion/115952/zotero-7-beta-tag-to-annotation-not-saved-when-clicking-away

**Comment by abaevbog** [comment] 2024-07-15 16:57
These look like two separate issues. There must be some edge case with `blur` handling of the `editable-text` that would make edits not save when the focus leaves the field. It doesn't seem to happen very reliably so I'll try to reproduce it.

The issue with tags popup for annotations, though, seems fixed in #4231. Potentially because the popup is changed from `menupopup` to `panel` (which I think is more typical for a popup that has editable fields).

For comparison, this is the screen recording of tags popup now:

https://github.com/user-attachments/assets/d9ba9313-65d9-454e-a2f8-8dae781b81b3

And in that PR:

https://github.com/user-attachments/assets/80c5d5d5-04e4-4353-bf07-dcab6112b864

**Comment by abaevbog** [comment] 2024-07-15 19:30
I found the following situation in which edits to title or abstract fields won't get saved: edit the field, switch to another window, switch back to zotero window, click or tab away from the field. Then the edits get lost. 

Not sure if this is the same issue as what is being reported but possible.

**Closed** 2024-07-16 08:37 UTC
Labels: Bug, P2
