### ISSUE TITLE
how to aviod the gaint white space in the note editor windows

### ISSUE THREAD

**Issue by bigben446** [zotero/zotero#2672] opened 2022-06-24 16:09 UTC
gaint white space A and B in the note editor windows

https://img-mid.csdnimg.cn/release/static/image/mid/ask/719487580656112.jpg

**Comment by mrtcode** [comment] 2022-06-24 18:53
https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md

Duplicate of #2563.

**Closed by mrtcode** 2022-06-24 18:53 UTC
