### ISSUE TITLE
Package for Debian (and thus Ubuntu, Elementary OS, etc)

### ISSUE THREAD

**Issue by LeoTindall** [zotero/zotero#1608] opened 2018-12-15 05:06 UTC
Would the team be opposed to having packages created for Debian with appropriate metadata for Elementary OS? Could even be hooked up so that the pay-what-you-want for ElementaryOS could contribute to the project.

**Comment by dstillman** [comment] 2018-12-16 04:35
Dupe of https://github.com/zotero/zotero-standalone-build/issues/52

**Closed by dstillman** 2018-12-16 04:35 UTC
