### ISSUE TITLE
Support EZProxy HttpsHyphens option (on by default)

### ISSUE THREAD

**Issue by aurimasv** [zotero/zotero#721] opened 2015-05-21 02:44 UTC
i.e. recognize https://scholar-google-com.ezproxy.gc.cuny.edu as proxied https://scholar.google.com

See https://www.oclc.org/content/dam/support/ezproxy/documentation/pdf/ezproxy_referencemanual.pdf (page 63)

Re https://forums.zotero.org/discussion/49514/google-scholar-problem/ and, I'm sure, many others

**Comment by fbennett** [comment] 2015-05-21 02:56
Ouch. Serendipity.

Our library at Nagoya University has been completely broken for proxied access to Zotero for months. The cause turned out to be the *disabling* of HttpsHyphens. Without the option, EzProxy is unable (as far as staff could tell) to set a valid SSL certificate on all subdomains recognized by the proxy. With an invalid certificate, Zotero downloads were failing completely.

With the option, a single wildcard cert can serve all connections. I hadn't thought through to the fact that the remapping of the URL would break translators at the Zotero end.

**Comment by fbennett** [comment] 2015-05-22 00:30
This will be needed to get our local service running again, so I'll take it on - unless it's already high on the priority list. I'll need some hand-holding though.

If I read the source correctly at [xpcom.proxy.js#L302](https://github.com/zotero/zotero/blob/4.0/chrome/content/zotero/xpcom/proxy.js#L302) and [xpcom/proxy.js#L655](https://github.com/zotero/zotero/blob/4.0/chrome/content/zotero/xpcom/proxy.js#L655), the real host name is currently derived from the proxied address with regular expressions, and the replacement used in translator processing ultimately happens at [xpcom.proxy.js#L810](https://github.com/zotero/zotero/blob/4.0/chrome/content/zotero/xpcom/proxy.js#L810).

There is data loss with hyphen-replacement, so we'll need to acquire the literal hostname from somewhere. The [release note](https://www.oclc.org/support/services/ezproxy/release-notes.en.html) for EZproxy V3.0-V3.8 at least suggests that it should be lurking in the transaction. Assuming that's right, then how does this sound ...

For `properToProxy()`, would it do to introduce a specific placeholder, for use in the hostname schema, that forces hyphen-replacement? (that is, the period-to-hyphen replacement in that direction should be safe - but should only be done for proxies known to require it.)

For `proxyToProper()`, if the original hostname can be sniffed from the EzProxy transactions, would it do to capture it to memory on-the-fly for use in `Zotero.Proxies`? (that is, I'd like to pursue a fix that addresses the issue without adding a column to the [proxyHosts](https://github.com/zotero/zotero/blob/4.0/resource/schema/userdata.sql#L349) table.)

**Comment by aurimasv** [comment] 2015-05-22 00:50
I'd hold on before taking this on. For one, there's already #578 that I'm trying to get merged. But also, this (and the other PR) should probably go straight into 5.0 (api_syncing) branch.

>There is data loss with hyphen-replacement

Not sure I understand. Unless you mean that a host name may contain hyphens in the unproxied form. I think that's relatively rare and we can, at least for now, assume that it's not a big issue. From reading around, I was not able to find any reference to the original host that is being proxied, so I'm not really sure that we would have any way of fetching it.

>For properToProxy(), would it do to introduce a specific placeholder, for use in the hostname schema, that forces hyphen-replacement? (that is, the period-to-hyphen replacement in that direction should be safe - but should only be done for proxies known to require it.)

For non-saved proxies, this should be fairly simple, since we assign toProxy and fromProxy functions at the time we figure out the proxy. It does get more complicated for saved proxies though, since it would either require additional columns in the DB or some sort of special schema as you suggest. Any change in DB will definitely have to wait for 5.0.

**Comment by fbennett** [comment] 2015-05-22 00:53
Thanks. Will hold then.
> Not sure I understand. Unless you mean that a host name may contain hyphens in the unproxied form.
That's what I meant, yes. The release note for the EzProxy `HttpsHyphens` option specifically mentions such a case (www.lexis-nexis.com).

**Comment by fbennett** [comment] 2015-05-22 00:58
In the meantime, when our own refactored proxy service comes up I'll take a look at the transactions and cookies it produces, just in case it does expose a hint of the proper hostname.

**Comment by simonster** [comment] 2015-05-22 01:02
Eventually the proxy info should be moved out of the DB entirely and into a JSON file. But couldn't we just have "%y" in place of "%h" to indicate that periods in the host should be replaced with hyphens?

**Comment by aurimasv** [comment] 2015-08-18 18:40
Another HttpsHyphens encoded url form reported [here](https://forums.zotero.org/discussion/51201/beckonline-translator-is-not-working/)
`https://beck-2online-1beck-1de-1356251691.erf.sbb.spk-berlin.de/` (I think the `-2` part might mean that it's supposed to be replaced by `-` rather than `.` Not sure what `-1356251691` is supposed to mean)

**Comment by zuphilip** [comment] 2015-08-18 18:47
@aurimasv I guess, that the `-1356251691` means one point following the <a href="http://rzblx10.uni-regensburg.de/dbinfo/detail.php?bib_id=sbb&colors=&ocolors=&lett=fs&tid=0&titel_id=1168">internal database number</a> `356251691`. Thus, IMO the whole url would encode to `https://beck-online.beck.de.356251691.erf.sbb.spk-berlin.de/`

**Comment by aurimasv** [comment] 2015-08-18 18:54
The number should be insignificant to us, no?

**Comment by aurimasv** [comment] 2015-08-18 19:00
Also, like you said on the forums, this is a HAN server proxy, not EZProxy. We'll account for it at the same time though.

**Comment by adomasven** [comment] 2016-12-12 13:54
Closed via 747c11c

**Closed by adomasven** 2016-12-12 13:54 UTC

**Comment by cambraca** [comment] 2022-10-20 17:11
Spent a while looking for those EZProxy release notes, they're archived here: https://web.archive.org/web/20150131011259/https://www.oclc.org/support/services/ezproxy/release-notes.en.html (the accordion widget didn't work for me but you can un-hide the "EZproxy V3.0-V3.8" section with devtools).
