### ISSUE TITLE
Note editor: Cursor doesn't appear after leaving math block

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero#2788] opened 2022-08-25 21:05 UTC
1. Create a new note.
2. Create a math block.
3. Press down-arrow to leave it.
4. The cursor disappears.

If you start typing, the text appears on the next line and the cursor reappears, but it doesn't appear before then. This doesn't happen if there's text on the line after the math node.

There's some general weirdness about the cursor in and around the math block — I can also get into trouble if I press Delete on an empty line after the math block, and I actually started getting an error:

```
 TypeError: range is null

    removeBlockIndent/<@resource://zotero/note-editor/editor.js:63914:1
    keydownHandler/<@resource://zotero/note-editor/editor.js:59856:23
    editHandlers.keydown/<@resource://zotero/note-editor/editor.js:57122:50
    someProp@resource://zotero/note-editor/editor.js:59261:50
    editHandlers.keydown@resource://zotero/note-editor/editor.js:57122:14
    initInput/view.input.eventHandlers[event]@resource://zotero/note-editor/editor.js:57044:17
```
(I can try to reproduce this more clearly if you can't reproduce it.)

**Comment by mrtcode** [comment] 2022-08-26 05:45
Could you test if this happens on fx102? Also https://github.com/zotero/zotero/issues/2793. Sounds like one of fx60 issues.

**Comment by mrtcode** [comment] 2024-07-26 12:43
Can't reproduce it anymore. It appears to be resolved by upgrading to a newer version of Firefox.

**Closed by mrtcode** 2024-07-26 12:43 UTC
Labels: Note Editor
