### ISSUE TITLE
Use correct version number for zotero.exe

### ISSUE THREAD

**Issue by Bitmapped** [zotero/zotero#1511] opened 2018-06-11 22:00 UTC
The zotero.exe file reports its version as 5.0.0.0 regardless of the 5.0.x release installed. (I have 5.0.48 at the moment.) This makes it hard to accurately manage Zotero using SCCM. Please start using the correct file version for zotero.org so we can set up our SCCM detection rules correctly.

**Comment by dstillman** [comment] 2022-02-22 07:06
Duplicate of https://github.com/zotero/zotero-standalone-build/issues/59

**Closed by dstillman** 2022-02-22 07:06 UTC
