### ISSUE TITLE
PDF worker: Ignore highlight comment if it's approximately equal to extracted text

### ISSUE THREAD

**Issue by mrtcode** [zotero/zotero#2517] opened 2022-04-08 05:24 UTC
https://forums.zotero.org/discussion/96180/duplicate-highlight-annotations

Also, to avoid cases like [this](https://github.com/jlegewie/zotfile/issues/460).

**Comment by dstillman** [comment] 2022-04-08 05:34
Duplicate of https://github.com/zotero/zotero/issues/2326

**Closed by dstillman** 2022-04-08 05:34 UTC

**Comment by mrtcode** [comment] 2022-04-08 06:54
Huh. Sorry.
