### ISSUE TITLE
attachment columns icon display bug

### ISSUE THREAD

**Issue by llity** [zotero/zotero#3594] opened 2024-01-26 07:29 UTC
On macos m2 device.
![image](https://github.com/zotero/zotero/assets/11771112/b7411386-1db4-44dc-bd57-68d27a84a2c8)

**Comment by dstillman** [comment] 2024-01-26 07:43
https://github.com/zotero/zotero/blob/main/CONTRIBUTING.md

https://forums.zotero.org/discussion/111077/zotero-7-beta-central-view-garbled-when-attachments-or-notes-is-the-first-column

Duplicate of https://github.com/zotero/zotero/issues/3582

**Closed by dstillman** 2024-01-26 07:43 UTC
