### ISSUE TITLE
Memory leakage in Zotero 7 on Apple silicon ?

### ISSUE THREAD

**Issue by kevinyuan** [zotero/zotero#3976] opened 2024-04-12 17:09 UTC
Memory goes high to 6+ G with just one single small (3 pages)  pdf file open.

Issues:

![image](https://github.com/zotero/zotero/assets/231197/7689e744-125a-4bfe-ad3f-67a34e70be3f)

![image](https://github.com/zotero/zotero/assets/231197/da7455a2-5d93-4bb5-bc0d-6e5d935d6c07)

S/W versions:

![image](https://github.com/zotero/zotero/assets/231197/5855550c-8273-4398-9cc9-638ffa112fb4)

![image](https://github.com/zotero/zotero/assets/231197/ca07ec66-c688-4277-aed9-ad16f50a7be5)

**Comment by dstillman** [comment] 2024-04-13 08:44
Note the text you deleted in order to post this — [we provide all support in the Zotero Forums](https://github.com/zotero/zotero/blob/main/CONTRIBUTING.md), so you should post there in the future. But since we're here, we can take a look.

Can you reproduce this after restarting Zotero with no tabs open? If so, what are the exact steps?

**Comment by dstillman** [comment] 2024-04-17 09:22
Closing due to non-response. Please post further reports to the forums.

**Closed as completed by dstillman** 2024-04-17 09:22 UTC

**Comment by dstillman** [comment] 2024-04-17 09:36
https://forums.zotero.org/discussion/113767/memory-leakage-in-zotero-7-on-apple-silicon
