### ISSUE TITLE
Remove Item from Collection shows confirmation dialog but does nothing if item is visible from subcollection

### ISSUE THREAD

**Issue by AbeJellinek** [zotero/zotero#2610] opened 2022-05-11 18:07 UTC
i.e. with Show Items from Subcollections enabled, if the item is in a subcollection but not the selected collection itself.

Seems like it should either remove the item from all subcollections or be disabled.

**Comment by dstillman** [comment] 2022-05-11 18:13
Duplicate of https://github.com/zotero/zotero/issues/1769

**Closed by dstillman** 2022-05-11 18:13 UTC
Labels: Interface

**Comment by AbeJellinek** [comment] 2022-05-11 18:47
Right, thanks.
