### ISSUE TITLE
Missing GTK2 translations

### ISSUE THREAD

**Issue by embar-** [zotero/zotero#1146] opened 2017-01-06 11:41 UTC
Both Zotero 4 and 5-beta variants has untranslated menu items like Undo, Redo, Cut, Copy, Paste, Delete, Select All, Find. It seems, that during build you did not include files like
`share/locale/*/LC_MESSAGES/gtk20-properties.mo`
`share/locale/*/LC_MESSAGES/gtk20.mo`

**Comment by dstillman** [comment] 2017-01-06 21:37
This isn't a GTK issue. I believe the problem is that, though we include all these strings in our localization files, editMenuOverlay.xul, the Mozilla file that creates these menu items and which [we include](https://github.com/zotero/zotero/blob/3741a75b1d75e089bdf01db4001e3adb24ada467/chrome/content/zotero/standalone/basicViewer.xul#L31), requires the Mozilla .dtd file itself, and so the built-in strings are used. Since we base Zotero on the English-language version of Firefox, only the English strings get used.

I think we can fix this just by using our own copy of editMenuOverlay.xul with that include removed. I'll take a look at this soon.

**Comment by dstillman** [comment] 2017-01-10 08:49
Fixed by 9fbdc77cac8cf82ed0de435b90ff9625a2d336b4

**Closed by dstillman** 2017-01-10 08:49 UTC
Labels: Localization
